STAGE_LOCAL = 'local'
STAGE_DEV = 'dev'
STAGE_LIVE  = 'live'

EMBEDDING_DIMENSION = 1536
MODEL_GPT_4O_MINI = 'gpt-4o-mini'
MODEL_GPT_4O = 'gpt-4o'
DEFAULT_MODEL = MODEL_GPT_4O_MINI

INTERNAL_API_KEY_HEADER = 'X-Internal-API-Key'

DEDUPLICATION_THRESHOLD = 0.85