service: ocs-backend

provider:
  name: aws
  runtime: provided
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 2048
  timeout: 900 
  environment:
    STAGE: ${opt:stage, 'dev'}
    ENVIRONMENT: "production"
    OPENSEARCH_HOST: search-essence-live-riaec66r4nmfd5fx6e7up63ypu.aos.us-east-1.on.aws
    OPENSEARCH_PORT: 443
    OPENSEARCH_INDEX: essence-news
    PG_HOST: postgres-db1.czwy8yo4ccyz.us-east-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: essence
    PG_USER: postgres

  ecr:
    images:
      ocsbackend:
        path: ./
        platform: linux/amd64

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
      allowCredentials: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:322521590770:*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - polly:SynthesizeSpeech
      Resource: "*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-west-1:322521590770:secret:*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-east-1:322521590770:secret:*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:us-east-1:322521590770:function:${self:service}-${self:provider.stage}-*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
    # Add permission for CloudWatch Events
    - Effect: Allow
      Action:
        - events:PutRule
        - events:PutTargets
      Resource: "*"
    # Add OpenSearch permissions
    - Effect: Allow
      Action:
        - es:ESHttp*
      Resource: "arn:aws:es:us-east-1:322521590770:domain/essence-dev/*"
    # Add ECR permissions
    - Effect: Allow
      Action:
        - ecr:GetAuthorizationToken
        - ecr:BatchCheckLayerAvailability
        - ecr:GetDownloadUrlForLayer
        - ecr:BatchGetImage
      Resource: "*"

functions:
  app:
    image:
      name: ocsbackend
    events:
      - httpApi: 
          path: /internal/{any+}
          method: '*'
          cors: false
      - httpApi:
          path: /test/{any+}
          method: '*'
          cors: false
      - httpApi:
          path: /{any+}
          method: '*'

  parseFeedsScheduled:
    image:
      name: ocsbackend
    events:
      - schedule: cron(0 6 * * ? *)  # Run at 6:00 AM UTC every day
      - schedule: cron(0 15 * * ? *)  # Run at 2:30 PM UTC every day
    maximumRetryAttempts: 0  # Set to 0 to disable retries for asynchronous invocations
